name: Check Pull Request Quality

# On any pull request targetting master
on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    # Lint all manifests
    - uses: lra/setup-kubeval@v1
    - name: Lint k8s manifest files
      run: kubeval -d cluster,apps --ignore-missing-schemas
